package com.example.xquareinterviewassignment.configuration.properties

import org.springframework.boot.context.properties.ConfigurationPropertiesScan
import org.springframework.context.annotation.Configuration

@ConfigurationPropertiesScan
@Configuration
class ConfigurationPropertiesScanConfig